# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f6e584ca09ebd7b876fc4c5077bc0639cbb72865248c30f7d236cc79060d12aa1937dc21c35a1778760e6e4704d3b6b9fd536a52fa4be9559da1b1af4464c7

test:
  secret_key_base: 246de4532b1cea19e1285273a4d9bb3eb673ee61508410ade359cc0c405d28db078052af1d579a1b788de69f8f29b5d48af5fc8a9c4c20d724c247bd11607612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
